//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Xerox.EIP.CloudPrint
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS-PrintService", Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
    public partial class WSPrintServiceService : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback GetInterfaceVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitiatePrintJobURLOperationCompleted;
        
        /// <remarks/>
        public WSPrintServiceService() {
            this.Url = "http://xerox-device-address/webservices/WS-PrintService/1";
        }
        
        /// <remarks/>
        public event GetInterfaceVersionCompletedEventHandler GetInterfaceVersionCompleted;
        
        /// <remarks/>
        public event InitiatePrintJobURLCompletedEventHandler InitiatePrintJobURLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.namespaces.xerox.com/enterprise/WS-PrintService/1/GetInterfaceVersion", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetInterfaceVersionResponse", Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
        public GetInterfaceVersionResponseType GetInterfaceVersion([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.xerox.com/webservices/WS-PrintService/1")] GetInterfaceVersionRequestType GetInterfaceVersionRequest) {
            object[] results = this.Invoke("GetInterfaceVersion", new object[] {
                        GetInterfaceVersionRequest});
            return ((GetInterfaceVersionResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInterfaceVersion(GetInterfaceVersionRequestType GetInterfaceVersionRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInterfaceVersion", new object[] {
                        GetInterfaceVersionRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetInterfaceVersionResponseType EndGetInterfaceVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetInterfaceVersionResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetInterfaceVersionAsync(GetInterfaceVersionRequestType GetInterfaceVersionRequest) {
            this.GetInterfaceVersionAsync(GetInterfaceVersionRequest, null);
        }
        
        /// <remarks/>
        public void GetInterfaceVersionAsync(GetInterfaceVersionRequestType GetInterfaceVersionRequest, object userState) {
            if ((this.GetInterfaceVersionOperationCompleted == null)) {
                this.GetInterfaceVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInterfaceVersionOperationCompleted);
            }
            this.InvokeAsync("GetInterfaceVersion", new object[] {
                        GetInterfaceVersionRequest}, this.GetInterfaceVersionOperationCompleted, userState);
        }
        
        private void OnGetInterfaceVersionOperationCompleted(object arg) {
            if ((this.GetInterfaceVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInterfaceVersionCompleted(this, new GetInterfaceVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.namespaces.xerox.com/enterprise/WS-PrintService/1/InitiatePrintJobURL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("InitiatePrintJobURLResponse", Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
        public InitiatePrintJobURLResponseType InitiatePrintJobURL([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.xerox.com/webservices/WS-PrintService/1")] InitiatePrintJobURLRequestType InitiatePrintJobURLRequest) {
            object[] results = this.Invoke("InitiatePrintJobURL", new object[] {
                        InitiatePrintJobURLRequest});
            return ((InitiatePrintJobURLResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInitiatePrintJobURL(InitiatePrintJobURLRequestType InitiatePrintJobURLRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InitiatePrintJobURL", new object[] {
                        InitiatePrintJobURLRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public InitiatePrintJobURLResponseType EndInitiatePrintJobURL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InitiatePrintJobURLResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void InitiatePrintJobURLAsync(InitiatePrintJobURLRequestType InitiatePrintJobURLRequest) {
            this.InitiatePrintJobURLAsync(InitiatePrintJobURLRequest, null);
        }
        
        /// <remarks/>
        public void InitiatePrintJobURLAsync(InitiatePrintJobURLRequestType InitiatePrintJobURLRequest, object userState) {
            if ((this.InitiatePrintJobURLOperationCompleted == null)) {
                this.InitiatePrintJobURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitiatePrintJobURLOperationCompleted);
            }
            this.InvokeAsync("InitiatePrintJobURL", new object[] {
                        InitiatePrintJobURLRequest}, this.InitiatePrintJobURLOperationCompleted, userState);
        }
        
        private void OnInitiatePrintJobURLOperationCompleted(object arg) {
            if ((this.InitiatePrintJobURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitiatePrintJobURLCompleted(this, new InitiatePrintJobURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
    public partial class GetInterfaceVersionRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
    public partial class InitiatePrintJobURLResponseType {
        
        private string jobIdField;
        
        /// <remarks/>
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
    public partial class InitiatePrintJobURLRequestType {
        
        private string printDocumentURLField;
        
        private string jobModelSchemaCommon_PrintJobTicketField;
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string PrintDocumentURL {
            get {
                return this.printDocumentURLField;
            }
            set {
                this.printDocumentURLField = value;
            }
        }
        
        /// <remarks/>
        public string JobModelSchemaCommon_PrintJobTicket {
            get {
                return this.jobModelSchemaCommon_PrintJobTicketField;
            }
            set {
                this.jobModelSchemaCommon_PrintJobTicketField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
    public partial class InterfaceVersionType {
        
        private short majorVersionField;
        
        private short minorVersionField;
        
        private short revisionField;
        
        /// <remarks/>
        public short MajorVersion {
            get {
                return this.majorVersionField;
            }
            set {
                this.majorVersionField = value;
            }
        }
        
        /// <remarks/>
        public short MinorVersion {
            get {
                return this.minorVersionField;
            }
            set {
                this.minorVersionField = value;
            }
        }
        
        /// <remarks/>
        public short Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/webservices/WS-PrintService/1")]
    public partial class GetInterfaceVersionResponseType {
        
        private InterfaceVersionType versionField;
        
        /// <remarks/>
        public InterfaceVersionType Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetInterfaceVersionCompletedEventHandler(object sender, GetInterfaceVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInterfaceVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInterfaceVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetInterfaceVersionResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetInterfaceVersionResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void InitiatePrintJobURLCompletedEventHandler(object sender, InitiatePrintJobURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitiatePrintJobURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitiatePrintJobURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InitiatePrintJobURLResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitiatePrintJobURLResponseType)(this.results[0]));
            }
        }
    }
}
