//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3649
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Xerox.EIP.JobManagement
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JobManagementBinding", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class JobManagementService : Microsoft.Web.Services3.WebServicesClientProtocol{
        
        private System.Threading.SendOrPostCallback GetInterfaceVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListActiveJobQueueOperationCompleted;
        
        private SecurityHeaderType securityField;
        
        private System.Threading.SendOrPostCallback ListActiveJobQueueSecureOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListCompletedJobQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListCompletedJobQueueSecureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJobDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJobDetailsSecureOperationCompleted;
        
        private System.Threading.SendOrPostCallback PauseJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback PauseJobSecureOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelJobSecureOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResumeJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResumeJobSecureOperationCompleted;
        
        /// <remarks/>
        public JobManagementService() {
            this.Url = "http://xerox-device-address/webservices/JobManagement/1";
        }
        
        public SecurityHeaderType Security {
            get {
                return this.securityField;
            }
            set {
                this.securityField = value;
            }
        }
        
        /// <remarks/>
        public event GetInterfaceVersionCompletedEventHandler GetInterfaceVersionCompleted;
        
        /// <remarks/>
        public event ListActiveJobQueueCompletedEventHandler ListActiveJobQueueCompleted;
        
        /// <remarks/>
        public event ListActiveJobQueueSecureCompletedEventHandler ListActiveJobQueueSecureCompleted;
        
        /// <remarks/>
        public event ListCompletedJobQueueCompletedEventHandler ListCompletedJobQueueCompleted;
        
        /// <remarks/>
        public event ListCompletedJobQueueSecureCompletedEventHandler ListCompletedJobQueueSecureCompleted;
        
        /// <remarks/>
        public event GetJobDetailsCompletedEventHandler GetJobDetailsCompleted;
        
        /// <remarks/>
        public event GetJobDetailsSecureCompletedEventHandler GetJobDetailsSecureCompleted;
        
        /// <remarks/>
        public event PauseJobCompletedEventHandler PauseJobCompleted;
        
        /// <remarks/>
        public event PauseJobSecureCompletedEventHandler PauseJobSecureCompleted;
        
        /// <remarks/>
        public event CancelJobCompletedEventHandler CancelJobCompleted;
        
        /// <remarks/>
        public event CancelJobSecureCompletedEventHandler CancelJobSecureCompleted;
        
        /// <remarks/>
        public event ResumeJobCompletedEventHandler ResumeJobCompleted;
        
        /// <remarks/>
        public event ResumeJobSecureCompletedEventHandler ResumeJobSecureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.namespaces.xerox.com/enterprise/JobManagement/1/GetInterfaceVersion", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetInterfaceVersionResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public GetInterfaceVersionResponseType GetInterfaceVersion([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] GetInterfaceVersionRequestType GetInterfaceVersionRequest) {
            object[] results = this.Invoke("GetInterfaceVersion", new object[] {
                        GetInterfaceVersionRequest});
            return ((GetInterfaceVersionResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInterfaceVersion(GetInterfaceVersionRequestType GetInterfaceVersionRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInterfaceVersion", new object[] {
                        GetInterfaceVersionRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetInterfaceVersionResponseType EndGetInterfaceVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetInterfaceVersionResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetInterfaceVersionAsync(GetInterfaceVersionRequestType GetInterfaceVersionRequest) {
            this.GetInterfaceVersionAsync(GetInterfaceVersionRequest, null);
        }
        
        /// <remarks/>
        public void GetInterfaceVersionAsync(GetInterfaceVersionRequestType GetInterfaceVersionRequest, object userState) {
            if ((this.GetInterfaceVersionOperationCompleted == null)) {
                this.GetInterfaceVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInterfaceVersionOperationCompleted);
            }
            this.InvokeAsync("GetInterfaceVersion", new object[] {
                        GetInterfaceVersionRequest}, this.GetInterfaceVersionOperationCompleted, userState);
        }
        
        private void OnGetInterfaceVersionOperationCompleted(object arg) {
            if ((this.GetInterfaceVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInterfaceVersionCompleted(this, new GetInterfaceVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.namespaces.xerox.com/enterprise/JobManagement/1/ListActiveJobQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListActiveJobQueueResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public ListQueueResponseType ListActiveJobQueue([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] ListJobQueueRequestType ListActiveJobQueueRequest) {
            object[] results = this.Invoke("ListActiveJobQueue", new object[] {
                        ListActiveJobQueueRequest});
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListActiveJobQueue(ListJobQueueRequestType ListActiveJobQueueRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListActiveJobQueue", new object[] {
                        ListActiveJobQueueRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ListQueueResponseType EndListActiveJobQueue(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ListActiveJobQueueAsync(ListJobQueueRequestType ListActiveJobQueueRequest) {
            this.ListActiveJobQueueAsync(ListActiveJobQueueRequest, null);
        }
        
        /// <remarks/>
        public void ListActiveJobQueueAsync(ListJobQueueRequestType ListActiveJobQueueRequest, object userState) {
            if ((this.ListActiveJobQueueOperationCompleted == null)) {
                this.ListActiveJobQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListActiveJobQueueOperationCompleted);
            }
            this.InvokeAsync("ListActiveJobQueue", new object[] {
                        ListActiveJobQueueRequest}, this.ListActiveJobQueueOperationCompleted, userState);
        }
        
        private void OnListActiveJobQueueOperationCompleted(object arg) {
            if ((this.ListActiveJobQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListActiveJobQueueCompleted(this, new ListActiveJobQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.namespaces.xerox.com/enterprise/JobManagement/1/ListActiveJobQueueSecu" +
            "re", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListActiveJobQueueSecureResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public ListQueueResponseType ListActiveJobQueueSecure([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] ListJobQueueSecureRequestType ListActiveJobQueueSecureRequest) {
            object[] results = this.Invoke("ListActiveJobQueueSecure", new object[] {
                        ListActiveJobQueueSecureRequest});
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListActiveJobQueueSecure(ListJobQueueSecureRequestType ListActiveJobQueueSecureRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListActiveJobQueueSecure", new object[] {
                        ListActiveJobQueueSecureRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ListQueueResponseType EndListActiveJobQueueSecure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ListActiveJobQueueSecureAsync(ListJobQueueSecureRequestType ListActiveJobQueueSecureRequest) {
            this.ListActiveJobQueueSecureAsync(ListActiveJobQueueSecureRequest, null);
        }
        
        /// <remarks/>
        public void ListActiveJobQueueSecureAsync(ListJobQueueSecureRequestType ListActiveJobQueueSecureRequest, object userState) {
            if ((this.ListActiveJobQueueSecureOperationCompleted == null)) {
                this.ListActiveJobQueueSecureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListActiveJobQueueSecureOperationCompleted);
            }
            this.InvokeAsync("ListActiveJobQueueSecure", new object[] {
                        ListActiveJobQueueSecureRequest}, this.ListActiveJobQueueSecureOperationCompleted, userState);
        }
        
        private void OnListActiveJobQueueSecureOperationCompleted(object arg) {
            if ((this.ListActiveJobQueueSecureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListActiveJobQueueSecureCompleted(this, new ListActiveJobQueueSecureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/ListCompletedJobQueue" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListCompletedJobQueueResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public ListQueueResponseType ListCompletedJobQueue([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] ListJobQueueRequestType ListCompletedJobQueueRequest) {
            object[] results = this.Invoke("ListCompletedJobQueue", new object[] {
                        ListCompletedJobQueueRequest});
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListCompletedJobQueue(ListJobQueueRequestType ListCompletedJobQueueRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListCompletedJobQueue", new object[] {
                        ListCompletedJobQueueRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ListQueueResponseType EndListCompletedJobQueue(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ListCompletedJobQueueAsync(ListJobQueueRequestType ListCompletedJobQueueRequest) {
            this.ListCompletedJobQueueAsync(ListCompletedJobQueueRequest, null);
        }
        
        /// <remarks/>
        public void ListCompletedJobQueueAsync(ListJobQueueRequestType ListCompletedJobQueueRequest, object userState) {
            if ((this.ListCompletedJobQueueOperationCompleted == null)) {
                this.ListCompletedJobQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCompletedJobQueueOperationCompleted);
            }
            this.InvokeAsync("ListCompletedJobQueue", new object[] {
                        ListCompletedJobQueueRequest}, this.ListCompletedJobQueueOperationCompleted, userState);
        }
        
        private void OnListCompletedJobQueueOperationCompleted(object arg) {
            if ((this.ListCompletedJobQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCompletedJobQueueCompleted(this, new ListCompletedJobQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/ListCompletedJobQueue" +
            "Secure", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListCompletedJobQueueSecureResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public ListQueueResponseType ListCompletedJobQueueSecure([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] ListJobQueueSecureRequestType ListCompletedJobQueueSecureRequest) {
            object[] results = this.Invoke("ListCompletedJobQueueSecure", new object[] {
                        ListCompletedJobQueueSecureRequest});
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListCompletedJobQueueSecure(ListJobQueueSecureRequestType ListCompletedJobQueueSecureRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListCompletedJobQueueSecure", new object[] {
                        ListCompletedJobQueueSecureRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ListQueueResponseType EndListCompletedJobQueueSecure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListQueueResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ListCompletedJobQueueSecureAsync(ListJobQueueSecureRequestType ListCompletedJobQueueSecureRequest) {
            this.ListCompletedJobQueueSecureAsync(ListCompletedJobQueueSecureRequest, null);
        }
        
        /// <remarks/>
        public void ListCompletedJobQueueSecureAsync(ListJobQueueSecureRequestType ListCompletedJobQueueSecureRequest, object userState) {
            if ((this.ListCompletedJobQueueSecureOperationCompleted == null)) {
                this.ListCompletedJobQueueSecureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCompletedJobQueueSecureOperationCompleted);
            }
            this.InvokeAsync("ListCompletedJobQueueSecure", new object[] {
                        ListCompletedJobQueueSecureRequest}, this.ListCompletedJobQueueSecureOperationCompleted, userState);
        }
        
        private void OnListCompletedJobQueueSecureOperationCompleted(object arg) {
            if ((this.ListCompletedJobQueueSecureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCompletedJobQueueSecureCompleted(this, new ListCompletedJobQueueSecureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.namespaces.xerox.com/enterprise/JobManagement/1/GetJobDetails", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetJobDetailsResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public GetJobDetailsResponseType GetJobDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] GetJobDetailsRequestType GetJobDetailsRequest) {
            object[] results = this.Invoke("GetJobDetails", new object[] {
                        GetJobDetailsRequest});
            return ((GetJobDetailsResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetJobDetails(GetJobDetailsRequestType GetJobDetailsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetJobDetails", new object[] {
                        GetJobDetailsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetJobDetailsResponseType EndGetJobDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetJobDetailsResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetJobDetailsAsync(GetJobDetailsRequestType GetJobDetailsRequest) {
            this.GetJobDetailsAsync(GetJobDetailsRequest, null);
        }
        
        /// <remarks/>
        public void GetJobDetailsAsync(GetJobDetailsRequestType GetJobDetailsRequest, object userState) {
            if ((this.GetJobDetailsOperationCompleted == null)) {
                this.GetJobDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJobDetailsOperationCompleted);
            }
            this.InvokeAsync("GetJobDetails", new object[] {
                        GetJobDetailsRequest}, this.GetJobDetailsOperationCompleted, userState);
        }
        
        private void OnGetJobDetailsOperationCompleted(object arg) {
            if ((this.GetJobDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJobDetailsCompleted(this, new GetJobDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.namespaces.xerox.com/enterprise/JobManagement/1/GetJobDetailsSecure", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetJobDetailsSecureResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public GetJobDetailsSecureResponseType GetJobDetailsSecure([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] GetJobDetailsSecureRequestType GetJobDetailsSecureRequest) {
            object[] results = this.Invoke("GetJobDetailsSecure", new object[] {
                        GetJobDetailsSecureRequest});
            return ((GetJobDetailsSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetJobDetailsSecure(GetJobDetailsSecureRequestType GetJobDetailsSecureRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetJobDetailsSecure", new object[] {
                        GetJobDetailsSecureRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetJobDetailsSecureResponseType EndGetJobDetailsSecure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetJobDetailsSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetJobDetailsSecureAsync(GetJobDetailsSecureRequestType GetJobDetailsSecureRequest) {
            this.GetJobDetailsSecureAsync(GetJobDetailsSecureRequest, null);
        }
        
        /// <remarks/>
        public void GetJobDetailsSecureAsync(GetJobDetailsSecureRequestType GetJobDetailsSecureRequest, object userState) {
            if ((this.GetJobDetailsSecureOperationCompleted == null)) {
                this.GetJobDetailsSecureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJobDetailsSecureOperationCompleted);
            }
            this.InvokeAsync("GetJobDetailsSecure", new object[] {
                        GetJobDetailsSecureRequest}, this.GetJobDetailsSecureOperationCompleted, userState);
        }
        
        private void OnGetJobDetailsSecureOperationCompleted(object arg) {
            if ((this.GetJobDetailsSecureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJobDetailsSecureCompleted(this, new GetJobDetailsSecureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/PauseJob", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PauseJobResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public PauseJobResponseType PauseJob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] JobRequestType PauseJobRequest) {
            object[] results = this.Invoke("PauseJob", new object[] {
                        PauseJobRequest});
            return ((PauseJobResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPauseJob(JobRequestType PauseJobRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PauseJob", new object[] {
                        PauseJobRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public PauseJobResponseType EndPauseJob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PauseJobResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void PauseJobAsync(JobRequestType PauseJobRequest) {
            this.PauseJobAsync(PauseJobRequest, null);
        }
        
        /// <remarks/>
        public void PauseJobAsync(JobRequestType PauseJobRequest, object userState) {
            if ((this.PauseJobOperationCompleted == null)) {
                this.PauseJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPauseJobOperationCompleted);
            }
            this.InvokeAsync("PauseJob", new object[] {
                        PauseJobRequest}, this.PauseJobOperationCompleted, userState);
        }
        
        private void OnPauseJobOperationCompleted(object arg) {
            if ((this.PauseJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PauseJobCompleted(this, new PauseJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/PauseJobSecure", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PauseJobSecureResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public PauseJobSecureResponseType PauseJobSecure([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] JobSecureRequestType PauseJobSecureRequest) {
            object[] results = this.Invoke("PauseJobSecure", new object[] {
                        PauseJobSecureRequest});
            return ((PauseJobSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPauseJobSecure(JobSecureRequestType PauseJobSecureRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PauseJobSecure", new object[] {
                        PauseJobSecureRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public PauseJobSecureResponseType EndPauseJobSecure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PauseJobSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void PauseJobSecureAsync(JobSecureRequestType PauseJobSecureRequest) {
            this.PauseJobSecureAsync(PauseJobSecureRequest, null);
        }
        
        /// <remarks/>
        public void PauseJobSecureAsync(JobSecureRequestType PauseJobSecureRequest, object userState) {
            if ((this.PauseJobSecureOperationCompleted == null)) {
                this.PauseJobSecureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPauseJobSecureOperationCompleted);
            }
            this.InvokeAsync("PauseJobSecure", new object[] {
                        PauseJobSecureRequest}, this.PauseJobSecureOperationCompleted, userState);
        }
        
        private void OnPauseJobSecureOperationCompleted(object arg) {
            if ((this.PauseJobSecureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PauseJobSecureCompleted(this, new PauseJobSecureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/CancelJob", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CancelJobResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public CancelJobResponseType CancelJob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] JobRequestType CancelJobRequest) {
            object[] results = this.Invoke("CancelJob", new object[] {
                        CancelJobRequest});
            return ((CancelJobResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCancelJob(JobRequestType CancelJobRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelJob", new object[] {
                        CancelJobRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public CancelJobResponseType EndCancelJob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CancelJobResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CancelJobAsync(JobRequestType CancelJobRequest) {
            this.CancelJobAsync(CancelJobRequest, null);
        }
        
        /// <remarks/>
        public void CancelJobAsync(JobRequestType CancelJobRequest, object userState) {
            if ((this.CancelJobOperationCompleted == null)) {
                this.CancelJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelJobOperationCompleted);
            }
            this.InvokeAsync("CancelJob", new object[] {
                        CancelJobRequest}, this.CancelJobOperationCompleted, userState);
        }
        
        private void OnCancelJobOperationCompleted(object arg) {
            if ((this.CancelJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelJobCompleted(this, new CancelJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/CancelJobSecure", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CancelJobSecureResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public CancelJobSecureResponseType CancelJobSecure([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] JobSecureRequestType CancelJobSecureRequest) {
            object[] results = this.Invoke("CancelJobSecure", new object[] {
                        CancelJobSecureRequest});
            return ((CancelJobSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCancelJobSecure(JobSecureRequestType CancelJobSecureRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelJobSecure", new object[] {
                        CancelJobSecureRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public CancelJobSecureResponseType EndCancelJobSecure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CancelJobSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CancelJobSecureAsync(JobSecureRequestType CancelJobSecureRequest) {
            this.CancelJobSecureAsync(CancelJobSecureRequest, null);
        }
        
        /// <remarks/>
        public void CancelJobSecureAsync(JobSecureRequestType CancelJobSecureRequest, object userState) {
            if ((this.CancelJobSecureOperationCompleted == null)) {
                this.CancelJobSecureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelJobSecureOperationCompleted);
            }
            this.InvokeAsync("CancelJobSecure", new object[] {
                        CancelJobSecureRequest}, this.CancelJobSecureOperationCompleted, userState);
        }
        
        private void OnCancelJobSecureOperationCompleted(object arg) {
            if ((this.CancelJobSecureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelJobSecureCompleted(this, new CancelJobSecureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/ResumeJob", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResumeJobResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public ResumeJobResponseType ResumeJob([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] JobRequestType ResumeJobRequest) {
            object[] results = this.Invoke("ResumeJob", new object[] {
                        ResumeJobRequest});
            return ((ResumeJobResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginResumeJob(JobRequestType ResumeJobRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ResumeJob", new object[] {
                        ResumeJobRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResumeJobResponseType EndResumeJob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResumeJobResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ResumeJobAsync(JobRequestType ResumeJobRequest) {
            this.ResumeJobAsync(ResumeJobRequest, null);
        }
        
        /// <remarks/>
        public void ResumeJobAsync(JobRequestType ResumeJobRequest, object userState) {
            if ((this.ResumeJobOperationCompleted == null)) {
                this.ResumeJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResumeJobOperationCompleted);
            }
            this.InvokeAsync("ResumeJob", new object[] {
                        ResumeJobRequest}, this.ResumeJobOperationCompleted, userState);
        }
        
        private void OnResumeJobOperationCompleted(object arg) {
            if ((this.ResumeJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResumeJobCompleted(this, new ResumeJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://xml.namespaces.xerox.com/enterprise/JobManagement/1/ResumeJobSecure", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResumeJobSecureResponse", Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
        public ResumeJobSecureResponseType ResumeJobSecure([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")] JobSecureRequestType ResumeJobSecureRequest) {
            object[] results = this.Invoke("ResumeJobSecure", new object[] {
                        ResumeJobSecureRequest});
            return ((ResumeJobSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginResumeJobSecure(JobSecureRequestType ResumeJobSecureRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ResumeJobSecure", new object[] {
                        ResumeJobSecureRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResumeJobSecureResponseType EndResumeJobSecure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResumeJobSecureResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ResumeJobSecureAsync(JobSecureRequestType ResumeJobSecureRequest) {
            this.ResumeJobSecureAsync(ResumeJobSecureRequest, null);
        }
        
        /// <remarks/>
        public void ResumeJobSecureAsync(JobSecureRequestType ResumeJobSecureRequest, object userState) {
            if ((this.ResumeJobSecureOperationCompleted == null)) {
                this.ResumeJobSecureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResumeJobSecureOperationCompleted);
            }
            this.InvokeAsync("ResumeJobSecure", new object[] {
                        ResumeJobSecureRequest}, this.ResumeJobSecureOperationCompleted, userState);
        }
        
        private void OnResumeJobSecureOperationCompleted(object arg) {
            if ((this.ResumeJobSecureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResumeJobSecureCompleted(this, new ResumeJobSecureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    [System.Xml.Serialization.XmlRootAttribute("Security", Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "", IsNullable=false)]
    public partial class SecurityHeaderType : System.Web.Services.Protocols.SoapHeader {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class ResumeJobSecureResponseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class ResumeJobResponseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class CancelJobSecureResponseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class CancelJobResponseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class PauseJobSecureResponseType {
        
        private UserAuthCredentialsType userAuthCredentialsField;
        
        /// <remarks/>
        public UserAuthCredentialsType UserAuthCredentials {
            get {
                return this.userAuthCredentialsField;
            }
            set {
                this.userAuthCredentialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class UserAuthCredentialsType {
        
        private string usernameField;
        
        private string passwordField;
        
        private string domainField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class JobSecureRequestType {
        
        private JobIdentifier jobDataField;
        
        private string jobTypeField;
        
        private string pinNumberField;
        
        private UserAuthCredentialsType userAuthCredentialsField;
        
        /// <remarks/>
        public JobIdentifier JobData {
            get {
                return this.jobDataField;
            }
            set {
                this.jobDataField = value;
            }
        }
        
        /// <remarks/>
        public string JobType {
            get {
                return this.jobTypeField;
            }
            set {
                this.jobTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PinNumber {
            get {
                return this.pinNumberField;
            }
            set {
                this.pinNumberField = value;
            }
        }
        
        /// <remarks/>
        public UserAuthCredentialsType UserAuthCredentials {
            get {
                return this.userAuthCredentialsField;
            }
            set {
                this.userAuthCredentialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class JobIdentifier {
        
        private string jobIdentifierTypeField;
        
        private string jobIdentifierStringField;
        
        /// <remarks/>
        public string JobIdentifierType {
            get {
                return this.jobIdentifierTypeField;
            }
            set {
                this.jobIdentifierTypeField = value;
            }
        }
        
        /// <remarks/>
        public string JobIdentifierString {
            get {
                return this.jobIdentifierStringField;
            }
            set {
                this.jobIdentifierStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class PauseJobResponseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class JobRequestType {
        
        private JobIdentifier jobDataField;
        
        private string jobTypeField;
        
        /// <remarks/>
        public JobIdentifier JobData {
            get {
                return this.jobDataField;
            }
            set {
                this.jobDataField = value;
            }
        }
        
        /// <remarks/>
        public string JobType {
            get {
                return this.jobTypeField;
            }
            set {
                this.jobTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class GetJobDetailsSecureResponseType {
        
        private string jobInfoXmlDocumentField;
        
        /// <remarks/>
        public string JobInfoXmlDocument {
            get {
                return this.jobInfoXmlDocumentField;
            }
            set {
                this.jobInfoXmlDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class GetJobDetailsSecureRequestType {
        
        private JobIdentifier jobDataField;
        
        private string jobTypeField;
        
        private UserAuthCredentialsType userAuthCredentialsField;
        
        /// <remarks/>
        public JobIdentifier JobData {
            get {
                return this.jobDataField;
            }
            set {
                this.jobDataField = value;
            }
        }
        
        /// <remarks/>
        public string JobType {
            get {
                return this.jobTypeField;
            }
            set {
                this.jobTypeField = value;
            }
        }
        
        /// <remarks/>
        public UserAuthCredentialsType UserAuthCredentials {
            get {
                return this.userAuthCredentialsField;
            }
            set {
                this.userAuthCredentialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class GetJobDetailsResponseType {
        
        private string jobInfoXmlDocumentField;
        
        /// <remarks/>
        public string JobInfoXmlDocument {
            get {
                return this.jobInfoXmlDocumentField;
            }
            set {
                this.jobInfoXmlDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class GetJobDetailsRequestType {
        
        private JobIdentifier jobDataField;
        
        private string jobTypeField;
        
        /// <remarks/>
        public JobIdentifier JobData {
            get {
                return this.jobDataField;
            }
            set {
                this.jobDataField = value;
            }
        }
        
        /// <remarks/>
        public string JobType {
            get {
                return this.jobTypeField;
            }
            set {
                this.jobTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class ListJobQueueSecureRequestType {
        
        private UserAuthCredentialsType userAuthCredentialsField;
        
        /// <remarks/>
        public UserAuthCredentialsType UserAuthCredentials {
            get {
                return this.userAuthCredentialsField;
            }
            set {
                this.userAuthCredentialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class ListQueueResponseType {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class ListJobQueueRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class InterfaceVersionType {
        
        private short majorVersionField;
        
        private short minorVersionField;
        
        private short revisionField;
        
        /// <remarks/>
        public short MajorVersion {
            get {
                return this.majorVersionField;
            }
            set {
                this.majorVersionField = value;
            }
        }
        
        /// <remarks/>
        public short MinorVersion {
            get {
                return this.minorVersionField;
            }
            set {
                this.minorVersionField = value;
            }
        }
        
        /// <remarks/>
        public short Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class GetInterfaceVersionResponseType {
        
        private InterfaceVersionType versionField;
        
        /// <remarks/>
        public InterfaceVersionType Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.namespaces.xerox.com/enterprise/JobManagement/1")]
    public partial class GetInterfaceVersionRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetInterfaceVersionCompletedEventHandler(object sender, GetInterfaceVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInterfaceVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInterfaceVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetInterfaceVersionResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetInterfaceVersionResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ListActiveJobQueueCompletedEventHandler(object sender, ListActiveJobQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListActiveJobQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListActiveJobQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListQueueResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListQueueResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ListActiveJobQueueSecureCompletedEventHandler(object sender, ListActiveJobQueueSecureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListActiveJobQueueSecureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListActiveJobQueueSecureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListQueueResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListQueueResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ListCompletedJobQueueCompletedEventHandler(object sender, ListCompletedJobQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCompletedJobQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCompletedJobQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListQueueResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListQueueResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ListCompletedJobQueueSecureCompletedEventHandler(object sender, ListCompletedJobQueueSecureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCompletedJobQueueSecureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCompletedJobQueueSecureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListQueueResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListQueueResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetJobDetailsCompletedEventHandler(object sender, GetJobDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJobDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJobDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetJobDetailsResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetJobDetailsResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetJobDetailsSecureCompletedEventHandler(object sender, GetJobDetailsSecureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJobDetailsSecureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJobDetailsSecureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetJobDetailsSecureResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetJobDetailsSecureResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void PauseJobCompletedEventHandler(object sender, PauseJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PauseJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PauseJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PauseJobResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PauseJobResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void PauseJobSecureCompletedEventHandler(object sender, PauseJobSecureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PauseJobSecureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PauseJobSecureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PauseJobSecureResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PauseJobSecureResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CancelJobCompletedEventHandler(object sender, CancelJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelJobResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelJobResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CancelJobSecureCompletedEventHandler(object sender, CancelJobSecureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelJobSecureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelJobSecureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelJobSecureResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelJobSecureResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ResumeJobCompletedEventHandler(object sender, ResumeJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResumeJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResumeJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResumeJobResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResumeJobResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ResumeJobSecureCompletedEventHandler(object sender, ResumeJobSecureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResumeJobSecureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResumeJobSecureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResumeJobSecureResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResumeJobSecureResponseType)(this.results[0]));
            }
        }
    }
}
